### PR TITLE
Added methods to expose Video struct basic attributes

### PR DESCRIPTION
**Pull request by AndreaNicola**
For one of my projects I needed to extract the dimensions and duration from the video.

I realized that these fields were present within the Video struct and therefore, without using other libraries, it is convenient to expose these 3 new methods to retrieve the field values effortlessly.

Bye :-)

### CODE REVIEW

**Comment by HGriessel** [comment]
Hi Andrea, 

I know this is unconvetional I am a semi expereinced python developer learing go. 

I however want to start contributing to Opensource and this project does seem like a good entry point and would like to find out if you would be available for conversation on this.

**Comment by AndreaNicola** [comment]
😃

**Comment by mowshon** [comment]
@AndreaNicola Thanks for participating! I will analyse the changes and make sure to commit to them. I'm very happy to have your help!

**Comment by mowshon** [comment]
Approved the changes, but I'll remove the `Get` prefixes from the methods.

**Pull request merged**
